#! /bin/bash

file_name="$2"
folder_name="$1"

echo 'Start Recording Script'
rosbag record -O ./$folder_name/$file_name /gazebo/model_states --duration=45 __name:=my_bag
echo $txt_name
rostopic echo -b ./$folder_name/$file_name.bag -p /gazebo/model_states > ./$folder_name/$file_name.txt
